---
- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - cron
          - tmux
          - nano
          - redsocks
          - iptables-persistent
        state: present
        update_cache: yes
