---
- name: Configure EarnApp server
  hosts: all
  become: true

  vars:
    redsocks_chain_name: REDSOCKS

  tasks:

    # Step 0 — Wait for apt locks to be released
    # - name: Wait for dpkg lock to be released
    #   wait_for:
    #     path: /var/lib/dpkg/lock-frontend
    #     state: absent
    #     timeout: 60

    # - name: Wait for apt cache lock to be released
    #   wait_for:
    #     path: /var/lib/apt/lists/lock
    #     state: absent
    #     timeout: 60

    # Step 1 — Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
      tags:
        - update_cache

    # Step 2 — Install required packages
    - name: Install required packages
      apt:
        name:
          - cron
          - nano
          - redsocks
          - iptables-persistent
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive
        APT_LISTCHANGES_FRONTEND: none
      tags:
        - install_packages

    # Step 3 — Configure redsocks
    - name: Create /etc/redsocks.conf
      copy:
        dest: /etc/redsocks.conf
        content: |
          base {
              log_debug = off;
              log_info = on;
              log = "syslog:daemon";
              daemon = on;
              redirector = iptables;
          }

          redsocks {
              local_ip = 0.0.0.0;
              local_port = {{ redsocks_port }};
              ip = {{ proxy_ip }};
              port = {{ proxy_port }};
              type = socks5;
              login = "{{ proxy_user }}";
              password = "{{ proxy_pass }}";
          }
        owner: root
        group: root
        mode: '0644'
      tags:
        - configure_redsocks

    # Step 4 — Configure iptables (idempotent)
    - name: Delete REDSOCKS chain if exists
      command: iptables -t nat -X {{ redsocks_chain_name }}
      ignore_errors: yes
      tags:
        - iptables

    - name: Create REDSOCKS chain
      command: iptables -t nat -N {{ redsocks_chain_name }}
      args:
        creates: /tmp/redsocks_chain_created
      register: redsocks_chain_create
      changed_when: redsocks_chain_create.rc == 0
      failed_when: false
      tags:
        - iptables

    - name: Mark chain creation (local file flag)
      file:
        path: /tmp/redsocks_chain_created
        state: touch
      when: redsocks_chain_create.rc == 0
      tags:
        - iptables

    - name: Allow local traffic (0.0.0.0/8)
      iptables:
        table: nat
        chain: "{{ redsocks_chain_name }}"
        destination: 0.0.0.0/8
        jump: RETURN
        protocol: all
      tags:
        - iptables

    - name: Allow proxy IP (do not redirect proxy itself)
      iptables:
        table: nat
        chain: "{{ redsocks_chain_name }}"
        destination: "{{ proxy_ip }}"
        jump: RETURN
        protocol: all
      tags:
        - iptables

    - name: Redirect TCP traffic to redsocks port
      iptables:
        table: nat
        chain: "{{ redsocks_chain_name }}"
        protocol: tcp
        jump: REDIRECT
        to_ports: "{{ redsocks_port }}"
      tags:
        - iptables

    - name: Redirect OUTPUT chain through REDSOCKS
      iptables:
        table: nat
        chain: OUTPUT
        protocol: tcp
        jump: "{{ redsocks_chain_name }}"
      tags:
        - iptables

    - name: Save iptables rules
      command: netfilter-persistent save
      tags:
        - iptables

    # Step 5 — Systemd unit for redsocks
    - name: Create systemd unit for redsocks
      copy:
        dest: /etc/systemd/system/redsocks.service
        content: |
          [Unit]
          Description=Redsocks proxy redirector
          After=network.target

          [Service]
          Type=forking
          ExecStart=/usr/sbin/redsocks -c /etc/redsocks.conf
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd
      tags:
        - systemd

    - name: Enable and start redsocks service
      systemd:
        name: redsocks
        enabled: true
        state: started
        daemon_reload: true
      tags:
        - systemd

    # Step 6 — Reboot and check external IP
    - name: Reboot the server
      reboot:
      tags:
        - reboot

    - name: Get external IP using ifconfig.me
      shell: curl -s ifconfig.me
      register: public_ip
      tags:
        - check_ip

    - name: Show external IP
      debug:
        msg: "Current external IP: {{ public_ip.stdout }}"
      tags:
        - check_ip

    # Step 7 — Install EarnApp
    - name: Download EarnApp installation script
      get_url:
        url: https://brightdata.com/static/earnapp/install.sh
        dest: /tmp/earnapp.sh
        mode: '0755'
      tags:
        - earnapp

    - name: Run EarnApp installation script
        shell: yes | bash /tmp/earnapp.sh
        register: earnapp_result
      tags:
          - earnapp


    - name: Show EarnApp installation result
      debug:
        var: earnapp_result.stdout_lines
      tags:
        - earnapp

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
