---
- name: Setup randomized reboot cronjob every 2 hours
  hosts: all
  become: true

  tasks:
    - name: Remove all existing crontab entries
      ansible.builtin.shell: crontab -r || true

    - name: Generate random minute (0-59)
      ansible.builtin.shell: echo $((RANDOM % 60))
      register: rand_min
      changed_when: false

    - name: Add cron job for reboot with random offset
      ansible.builtin.cron:
        name: "Reboot every 2 hours randomized"
        minute: "{{ rand_min.stdout }}"
        hour: "*/2"
        job: "/sbin/reboot"
